import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import clsx from "clsx";
import { ThemeProvider, type DefaultTheme } from "styled-components";
import StyledComponentsRegistry from "../lib/registry";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

const theme: DefaultTheme = {
  colors: {
    primary: "#111",
    secondary: "#0070f3",
  },
};
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport:
    "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={clsx(
          inter.className,
          "min-h-screen bg-background antialiased"
        )}
        suppressHydrationWarning
      >
        <StyledComponentsRegistry>
          {" "}
          <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
            <div className="relative">{children}</div>
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
